import { Suspense, useMemo } from "react";
import { WALK_CONFIG } from "../../../config/walk.config";
import { usePathSpline } from "../../../hooks/usePathSpline";
import { useGridStore } from "../../../stores/useGridStore";
import * as THREE from "three";
import Grass from "../environment/Grass";

import GroundPlane from "../environment/GroundPlane";

import NatureItemFactory from "../nature/NatureItemFactory";

import PathRibbon1 from "./PathRibbon1";
import Birds from "../environment/Birds";
import Clouds from "../environment/Clouds";
import Hills from "../environment/Hills";

import { NATURE_ITEMS } from "../../../config/natureItems.config";
import {
  indexToAxial,
  axialToWorld,
  GRID_CONFIG,
} from "../../../config/grid.config";
import { seededRandom } from "../../../utils/seededRandom";

const DISTANT_TREES = [
  {
    id: "distant_tree_1",
    label: "distant tree 1",
    emoji: "🌲",
    description: "A tree used for distant background elements.",
    component: "",
    props: {},
    windAffected: true,
    windNode: "pine_leaves",
    groundOffset: 0,
    category: "tree",
  },
  {
    id: "distant_tree_2",
    label: "distant tree 2",
    emoji: "🌲",
    description: "A tree used for distant background elements.",
    component: "",
    props: {},
    windAffected: true,
    windNode: "pine_leaves",
    groundOffset: 0,
    category: "tree",
  },
  {
    id: "distant_tree_3",
    label: "distant tree 3",
    emoji: "🌲",
    description: "A tree used for distant background elements.",
    component: "",
    props: {},
    windAffected: true,
    windNode: "pine_leaves",
    groundOffset: 0,
    category: "tree",
  },
  {
    id: "distant_tree_4",
    label: "distant tree 4",
    emoji: "🌲",
    description: "A tree used for distant background elements.",
    component: "",
    props: {},
    windAffected: true,
    windNode: "pine_leaves",
    groundOffset: 0,
    category: "tree",
  },
  {
    id: "distant_tree_5",
    label: "distant tree 5",
    emoji: "🌲",
    description: "A tree used for distant background elements.",
    component: "",
    props: {},
    windAffected: true,
    windNode: "pine_leaves",
    groundOffset: 0,
    category: "tree",
  },
  {
    id: "distant_tree_6",
    label: "distant tree 6",
    emoji: "🌲",
    description: "A tree used for distant background elements.",
    component: "",
    props: {},
    windAffected: true,
    windNode: "pine_leaves",
    groundOffset: 0,
    category: "tree",
  },
];

// Background tree pool — all items in 'tree' category
const TREE_ITEMS = NATURE_ITEMS.filter((i) => i.category === "tree");

// Equal weights to start — increase a value to make that tree more common
const TREE_WEIGHTS = TREE_ITEMS.map(() => 1.0);

function pickRandomTree(rand: () => number): string {
  const totalWeight = TREE_WEIGHTS.reduce((a, b) => a + b, 0);
  let r = rand() * totalWeight;
  for (let i = 0; i < TREE_ITEMS.length; i++) {
    r -= TREE_WEIGHTS[i];
    if (r <= 0) return TREE_ITEMS[i].id;
  }
  return TREE_ITEMS[0].id;
}

function pickRandomDistantTree(rand: () => number): string {
  const TREE_ITEMS = DISTANT_TREES.filter((i) => i.category === "tree");
  const totalWeight = TREE_WEIGHTS.reduce((a, b) => a + b, 0);
  let r = rand() * totalWeight;
  for (let i = 0; i < TREE_ITEMS.length; i++) {
    r -= TREE_WEIGHTS[i];
    if (r <= 0) return TREE_ITEMS[i].id;
  }
  return TREE_ITEMS[0].id;
}

export default function WalkScene() {
  const path = useGridStore((s) => s.path);
  const { pathSet, adjacentSet } = useGridStore();
  const placedNature = useGridStore((s) => s.placedNature);

  const { pathCurve } = usePathSpline(path);

  // The ribbon geometry is generated by sampling points along the path curve and creating pairs of vertices offset to the left and right of the curve. These vertices are then connected to form triangles that create a continuous ribbon along the path. The width of the ribbon is determined by the WALK_CONFIG.pathBoundaryWidth, which specifies how far from the center of the path the edges should be. By using the tangents of the curve to calculate perpendicular vectors, we ensure that the ribbon correctly follows the curvature of the path, creating a visually appealing boundary effect.
  const ribbonGeometry = useMemo(() => {
    if (!pathCurve) return null;

    // The number of samples along the curve / path determines how smooth the ribbon will be. More samples create a smoother ribbon but require more vertices and can impact performance. In this case, we use 200 samples, which provides a good balance between visual quality and performance for typical path lengths in the game.
    const SAMPLES = 200;
    const RIBBON_Y = -0.02;
    const PATH_TILING_FACTOR = 15;

    // Each segment between two sampled points on the curve forms a quad (two triangles) that represents a portion of the ribbon. Since each quad has 6 vertices (3 for each triangle), we need to allocate enough space in the vertices array to hold all the vertices for the entire ribbon.
    const vertices = new Float32Array(SAMPLES * 6 * 3);
    const uvs = new Float32Array(SAMPLES * 6 * 2); // 2 floats per vertex
    let idx = 0;
    let uvIdx = 0;

    for (let i = 0; i < SAMPLES; i++) {
      const t0 = i / SAMPLES;
      const t1 = (i + 1) / SAMPLES;

      // For each pair of points along the curve, we calculate the center position and the tangent vector. The tangent vector gives us the direction of the path at that point, which we use to determine how to offset the vertices for the left and right edges of the ribbon.
      const center0 = pathCurve.getPointAt(t0);
      const center1 = pathCurve.getPointAt(t1);
      const tangent0 = pathCurve.getTangentAt(t0);
      const tangent1 = pathCurve.getTangentAt(t1);

      // Calculate the perpendicular vectors to the tangents in the horizontal plane (y=0). This gives us the direction to offset the vertices for the left and right edges of the ribbon. The perpendicular vector is obtained by swapping the x and z components of the tangent and negating one of them, which effectively rotates the tangent by 90 degrees in the horizontal plane.
      const perp0 = new THREE.Vector3(-tangent0.z, 0, tangent0.x);
      const perp1 = new THREE.Vector3(-tangent1.z, 0, tangent1.x);

      // We then create the left and right vertices for both points by offsetting the center position along the perpendicular vector. The amount of offset is determined by the WALK_CONFIG.pathBoundaryWidth, which specifies how far from the center of the path the edges of the ribbon should be. By adding and subtracting this offset from the center position, we create two vertices for each point: one on the left side of the path and one on the right side.
      const left0 = center0
        .clone()
        .addScaledVector(perp0, -WALK_CONFIG.pathRibbonWidth);
      const right0 = center0
        .clone()
        .addScaledVector(perp0, WALK_CONFIG.pathRibbonWidth);
      const left1 = center1
        .clone()
        .addScaledVector(perp1, -WALK_CONFIG.pathRibbonWidth);
      const right1 = center1
        .clone()
        .addScaledVector(perp1, WALK_CONFIG.pathRibbonWidth);

      //here's how the triangles are formed between the left and right vertices of consecutive points:
      // left0 -------- right0    ← sample i
      //   |          ╲    |
      //   |            ╲  |
      // left1 -------- right1    ← sample i+1

      //triangle 1 below: left0, right0, left1
      //triangle 2 below : right0, right1, left1
      vertices[idx++] = left0.x;
      vertices[idx++] = left0.y + RIBBON_Y;
      vertices[idx++] = left0.z;
      vertices[idx++] = right0.x;
      vertices[idx++] = right0.y + RIBBON_Y;
      vertices[idx++] = right0.z;
      vertices[idx++] = left1.x;
      vertices[idx++] = left1.y + RIBBON_Y;
      vertices[idx++] = left1.z;

      vertices[idx++] = right0.x;
      vertices[idx++] = right0.y + RIBBON_Y;
      vertices[idx++] = right0.z;
      vertices[idx++] = right1.x;
      vertices[idx++] = right1.y + RIBBON_Y;
      vertices[idx++] = right1.z;
      vertices[idx++] = left1.x;
      vertices[idx++] = left1.y + RIBBON_Y;
      vertices[idx++] = left1.z;

      //now calculate UVs for the triangles.  The V coordinate is based on the distance along the path, scaled by PATH_TILING_FACTOR to control how many times the texture repeats along the length of the ribbon. The U coordinate is simply 0 for left vertices and 1 for right vertices, which maps the texture across the width of the ribbon.
      const v0 = (i / SAMPLES) * PATH_TILING_FACTOR;
      const v1 = ((i + 1) / SAMPLES) * PATH_TILING_FACTOR;

      // Triangle 1: left0, right0, left1
      uvs[uvIdx++] = 0;
      uvs[uvIdx++] = v0; // left0
      uvs[uvIdx++] = 1;
      uvs[uvIdx++] = v0; // right0
      uvs[uvIdx++] = 0;
      uvs[uvIdx++] = v1; // left1

      // Triangle 2: right0, right1, left1
      uvs[uvIdx++] = 1;
      uvs[uvIdx++] = v0; // right0
      uvs[uvIdx++] = 1;
      uvs[uvIdx++] = v1; // right1
      uvs[uvIdx++] = 0;
      uvs[uvIdx++] = v1; // left1
    }

    const geometry = new THREE.BufferGeometry();
    geometry.setAttribute("position", new THREE.BufferAttribute(vertices, 3));
    geometry.setAttribute("uv", new THREE.BufferAttribute(uvs, 2));
    geometry.setAttribute("uv2", new THREE.BufferAttribute(uvs, 2)); // AO map
    geometry.computeVertexNormals();
    return geometry;
  }, [pathCurve]);

  const naturePositions = useMemo(() => {
    if (!pathCurve) return [];

    const placed: {
      key: string;
      itemId: string;
      position: THREE.Vector3;
      scale?: number;
    }[] = [];
    const placedPositions: THREE.Vector3[] = [];

    const NATURE_OFFSET = 1.0;
    const OFFSET_STEP = 0.8;
    const MAX_ATTEMPTS = 4;
    const MIN_SPACING = 1.5;

    Object.entries(placedNature).forEach(([key, itemId]) => {
      const [q, r] = key.split(",").map(Number);
      const { x, z } = axialToWorld(q, r);
      const tilePos = new THREE.Vector3(x, 0, z);

      // Find closest point on spline
      let closestT = 0;
      let closestDist = Infinity;
      for (let i = 0; i <= 200; i++) {
        const t = i / 200;
        const pt = pathCurve.getPointAt(t);
        const dist = pt.distanceTo(tilePos);
        if (dist < closestDist) {
          closestDist = dist;
          closestT = t;
        }
      }

      // Push direction — from closest path point toward tile
      const closestPoint = pathCurve.getPointAt(closestT);
      const pushDir = tilePos.clone().sub(closestPoint);
      pushDir.y = 0;
      pushDir.normalize();

      // Try increasing offsets until we find a clear position
      let finalPos: THREE.Vector3 | null = null;

      for (let attempt = 0; attempt < MAX_ATTEMPTS; attempt++) {
        const offset = NATURE_OFFSET + attempt * OFFSET_STEP;
        const candidatePos = tilePos.clone().addScaledVector(pushDir, offset);
        candidatePos.y = 0;

        // Check path clearance
        let tooCloseToPath = false;
        for (let i = 0; i <= 200; i++) {
          const t = i / 200;
          if (
            pathCurve.getPointAt(t).distanceTo(candidatePos) <
            WALK_CONFIG.pathBoundaryWidth
          ) {
            tooCloseToPath = true;
            break;
          }
        }
        if (tooCloseToPath) continue;

        // Check spacing from other placed items
        const tooCloseToOther = placedPositions.some(
          (p) => p.distanceTo(candidatePos) < MIN_SPACING,
        );
        if (tooCloseToOther) continue;

        // Position is good
        finalPos = candidatePos;
        break;
      }

      if (!finalPos) return; // all attempts failed, skip

      placedPositions.push(finalPos.clone());
      placed.push({ key, itemId, position: finalPos });
    });

    /////////////////////////////////////////////////////
    // Second pass — background trees in ring around path
    // This is a more relaxed placement, allowing trees to be placed further from the path, but still avoiding overlap with existing items and ensuring a minimum distance from the path.
    //////////////////////////////////////////////////////
    {
      const BG_TREE_MIN_DIST = WALK_CONFIG.pathBoundaryWidth + 13.5;
      const BG_TREE_MAX_DIST = WALK_CONFIG.pathBoundaryWidth + 68.0;
      const BG_TREE_MIN_SPACING = 2.5;
      const BG_TREE_SCALE = 1.0;
      const MAX_BACKGROUND_TREES = 180;
      const rand = seededRandom(42);

      let treeCount = 0;

      for (
        let row = 0;
        row < GRID_CONFIG.rows && treeCount < MAX_BACKGROUND_TREES;
        row++
      ) {
        for (
          let col = 0;
          col < GRID_CONFIG.cols && treeCount < MAX_BACKGROUND_TREES;
          col++
        ) {
          const { q, r } = indexToAxial(col, row);
          const { x, z } = axialToWorld(q, r);
          const tilePos = new THREE.Vector3(x, 0, z);
          const tileKey = `${q},${r}`;

          // Skip path, adjacent, and already placed tiles
          if (pathSet.has(tileKey)) continue;
          if (adjacentSet.has(tileKey)) continue;
          if (placedNature[tileKey]) continue;

          // Find closest spline point
          let closestDist = Infinity;
          let closestT = 0;
          for (let i = 0; i <= 200; i++) {
            const t = i / 200;
            const pt = pathCurve.getPointAt(t);
            const d = pt.distanceTo(tilePos);
            if (d < closestDist) {
              closestDist = d;
              closestT = t;
            }
          }

          // Only place in target zone
          if (closestDist < BG_TREE_MIN_DIST || closestDist > BG_TREE_MAX_DIST)
            continue;

          // Push slightly away from path
          const closestPoint = pathCurve.getPointAt(closestT);
          const pushDir = tilePos.clone().sub(closestPoint).normalize();
          const candidatePos = tilePos.clone().addScaledVector(pushDir, 0.5);
          candidatePos.y = 0;

          // Check spacing against all placed items
          const tooClose = placedPositions.some(
            (p) => p.distanceTo(candidatePos) < BG_TREE_MIN_SPACING,
          );
          if (tooClose) continue;

          // Place tree
          const itemId = pickRandomTree(rand);
          placedPositions.push(candidatePos.clone());
          placed.push({
            key: `bg_tree_${col}_${row}`,
            itemId,
            position: candidatePos,
            scale: BG_TREE_SCALE,
          });
          treeCount++;
        }
      }
    }

    //Third pass — background trees in ring around origin, outside of grid bounds
    {
      {
        const BG_TREE_MIN_DIST = 50; // world units from origin
        const BG_TREE_MAX_DIST = 85; // world units from origin
        const BG_TREE_MIN_SPACING = 3.5; // between trees
        const BG_TREE_SCALE = 1.0;
        const MAX_ATTEMPTS = 300; // how many random positions to try
        const MAX_TREES = 70;
        const rand = seededRandom(42);

        let treeCount = 0;
        let attempts = 0;

        while (treeCount < MAX_TREES && attempts < MAX_ATTEMPTS) {
          attempts++;

          // Random position in the ring
          const angle = rand() * Math.PI * 2;
          const dist =
            BG_TREE_MIN_DIST + rand() * (BG_TREE_MAX_DIST - BG_TREE_MIN_DIST);
          const x = Math.cos(angle) * dist;
          const z = Math.sin(angle) * dist;
          const candidatePos = new THREE.Vector3(x, 0, z);

          // Check spacing against all placed items
          const tooClose = placedPositions.some(
            (p) => p.distanceTo(candidatePos) < BG_TREE_MIN_SPACING,
          );
          if (tooClose) continue;

          // Place tree
          const itemId = pickRandomDistantTree(rand);

          placedPositions.push(candidatePos.clone());
          placed.push({
            key: `bg_tree_${attempts}`,
            itemId,
            position: candidatePos,
            scale: BG_TREE_SCALE,
          });
          treeCount++;
        }
      }
    }

    return placed;
  }, [pathCurve, placedNature]);

  return (
    <>
      {/* <Bush position={[0, 0.5, 0.0]} radius={0.5} /> */}
      {/* Ground plane */}
      {/* <mesh
        rotation={[-Math.PI / 2, 0, 0]}
        position={[0, -0.05, 0]}
        receiveShadow
        renderOrder={1}
      >
        <planeGeometry args={[400, 400]} />

        <meshStandardMaterial color="green" roughness={0.9} depthWrite={true} />
      </mesh> */}
      <Suspense fallback={null}>
        <GroundPlane />
      </Suspense>

      <Suspense fallback={null}>
        <Grass pathCurve={pathCurve} pathWidth={WALK_CONFIG.pathRibbonWidth} />
      </Suspense>

      {naturePositions.map(({ key, itemId, position, scale }) => (
        <NatureItemFactory
          key={key}
          itemId={itemId}
          position={[position.x, 0, position.z]}
          scale={scale}
        />
      ))}

      {/* Path ribbon */}
      {/* {ribbonGeometry && (
        <mesh geometry={ribbonGeometry} receiveShadow>
          <meshStandardMaterial color="#7a5c3a" roughness={0.8} />
        </mesh>
      )} */}

      <Suspense fallback={null}>
        <PathRibbon1 geometry={ribbonGeometry} />
      </Suspense>
      <Birds />
      <Clouds />
      <Hills />
    </>
  );
}
